### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by sanjay-kandpal** [SimformSolutionsPvtLtd/SS-ARTreasureHunt#5]
![bug](https://github.com/user-attachments/assets/4770ab71-8904-4306-8aab-d61d91aa9780)
black screen , and camera not opening.
after following all the steps mentioned and solving compile time error , i am getting this in android app. and there was no error.

**Comment by yashwantgowla-simform** [comment]
@sanjay-kandpal Thank you for using our repo and apologies for the issue caused!

Could you please provide us more details like the device details including Android version, Device model etc.? It would be more helpful to reproduce this error.

Looking forward to your response. Thank you!

**Comment by sanjay-kandpal** [comment]
Android version: 14. tried on samsung s23, nothing phone 2, motorola Edge 50 fusion.
Android version: 9, redmi note 7.

**Comment by sanjay-kandpal** [comment]
@yashwantgowla-simform any updates ?

**Comment by ankit-verma-simform** [comment]
Hello @sanjay-kandpal,

Thank you for your patience, and apologies for the delayed response.

I've taken a closer look at the issue, and it seems there are several possible causes for this behavior. Based on the device details alone, it’s difficult to pinpoint the exact cause. Some potential reasons for the issue include:

- Camera permission issues
- Incorrect ARCore configurations
- The wrong renderer pipeline being used
- Outdated or mismatched dependency versions
- Possibly unsupported AR devices (though this doesn't seem to be the case here)
- Other factors that may not be immediately obvious

There are already a number of related discussions in the community, which could provide some helpful insights. I recommend checking them out to see if any solutions apply to your specific situation.

Additionally, I've created and tested an AR project on my end. You may find it useful to refer to the configurations in this project to see if there are any discrepancies with your own setup. You can access the project using the link below:

[Project Link](https://drive.google.com/file/d/1YDvWQTxUinNL7wqMQ2kyVZK2or6_X9QM/view?usp=sharing)

I hope this helps clarify things and leads you in the right direction. If you have any further questions or need more assistance, feel free to reach out!
